- hosts: localhost
  tasks:
    - name: Install apt packages
      become: yes
      apt:
        pkg:
        - curl
        - network-manager
    - name: Remove dependencies that are no longer required
      become: yes
      apt:
        autoremove: yes
    - name: Retrieve ifname
      shell: nmcli -t device | grep ethern | cut -d ':' -f1 | head -n 1
      register: ifname
    - name: Add an Ethernet connection with static IP configuration
      community.general.nmcli:
        conn_name: debian-lan
        ifname: "{{ ifname.stdout }}"
        type: ethernet
        # we use a static IP instead of a range of IPs since there is
        # no dns server in this scenario which in make it imposible to
        # connect using the host name only
        ip4: 192.168.2.222
        gw4: 192.168.2.1
        dns4:
        - 8.8.8.8
        - 1.1.1.1
        state: present
        autoconnect: yes
    - name: Test if interfaces is present.
      stat:
        path: "/etc/network/interfaces"
      register: interfaces
    - name: Disable and bkp interfaces
      shell: mv /etc/network/interfaces /root/interfaces.bkp
      when: interfaces.stat.exists
    - name: Install or update k3s
      shell: curl -sfL https://get.k3s.io | sh -
    - name: Create ArgoCD namespace
      k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present
    - name: Download ArgoCD manifest to the cluster.
      get_url:
        url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        dest: /root/argocd.yaml
        mode: '0664'
    - name: Apply ArgoCD manifest to the cluster.
      kubernetes.core.k8s:
        state: present
        src: /root/argocd.yaml
