- hosts: localhost
  tasks:
    - name: Add an Ethernet connection with static IP configuration
      community.general.nmcli:
        conn_name: debian-lan
        ifname: '*'
        type: ethernet
        # we use a static IP instead of a range of IPs since there is
        # no dns server in this scenario which in make it imposible to
        # connect using the host name only
        ip4: 192.168.2.222
        gw4: 192.168.2.1
        dns4:
        - 8.8.8.8
        - 1.1.1.1
        state: present
    - name: Install or update k3s
      shell: curl -sfL https://get.k3s.io | sh -
