---
- name: Install apt packages
  become: yes
  apt:
    pkg:
    - zsh
- name: Test if oh-my-zsh is present.
  stat:
    path: "~/.oh-my-zsh"
  register: ohmyzsh
- name: Install "oh-my-zsh"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh.stat.exists